# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180204_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
